name: otomas
description: "Otomas Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.8

  intl: 0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  url_strategy: ^0.3.0

  provider: ^6.1.2
  path_provider: ^2.1.4
  dart_json_mapper: ^2.2.13
  property_change_notifier: ^0.4.0

  retrofit: ^4.4.1
  dio: ^5.7.0

  jwt_decode: ^0.3.1
  uuid: ^4.5.0

  auto_route: ^9.2.2
  reflectable: ^4.0.10

  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2

  maps_launcher: ^2.2.1
  url_launcher: ^6.3.0
  add_2_calendar: ^3.0.1

  mask_text_input_formatter: ^2.9.0
  expandable_page_view: ^1.0.17
  syncfusion_flutter_charts: ^23.2.4

  image_picker: ^1.1.2
  file_picker: ^8.1.2
  image_downloader_web: ^2.0.6
  flutter_image_compress: ^2.3.0
  record: ^5.1.2
  just_audio: ^0.9.40
  flutter_cupertino_datetime_picker: ^3.0.0
  ucg_interactable_svg: ^1.0.25

  photo_view: ^0.15.0
  flutter_svg: ^2.0.10+1

  animate_do: ^3.3.4
  avatar_glow: ^3.0.1
  shimmer: ^3.0.0

  fluttertoast: ^8.2.8
  adaptive_dialog: ^2.2.0

  flutter_html: ^3.0.0-beta.2

  google_api_availability: ^5.0.0
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  firebase_remote_config: ^5.1.0

  in_app_review: ^2.0.9
  paged_datatable: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0

  retrofit_generator:
    path: lib/packages/retrofit_generator/

dependency_overrides:
  intl: 0.19.0
  meta: ^1.15.0
  web: ^1.0.0
  

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: display-black-italic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black-Italic.otf

    - family: display-bold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
    
    - family: display-heavy-italic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy-Italic.otf

    - family: display-light-italic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light-Italic.otf

    - family: display-medium
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
    
    - family: display-regular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    
    - family: display-semi-bold-italic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semi-Bold-Italic.otf

    - family: display-thin-italic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin-Italic.otf

    - family: display-ultra-light-italic
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultra-Light-Italic.otf
