// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7fX3zAaC7UARBa-68N1paIHn-v3-ipM',
    appId: '1:567166482786:web:875fd28ada57e7e5b8d43b',
    messagingSenderId: '567166482786',
    projectId: 'property-listing-fc0de',
    authDomain: 'property-listing-fc0de.firebaseapp.com',
    storageBucket: 'property-listing-fc0de.appspot.com',
    measurementId: 'G-D787LLF2N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yzQrl6k_MoBcQKtDTEiM4LQPHh3BcV0',
    appId: '1:567166482786:android:446c6fe1c7e3c2dbb8d43b',
    messagingSenderId: '567166482786',
    projectId: 'property-listing-fc0de',
    storageBucket: 'property-listing-fc0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1up1MBUWZ6Gsy_i-xiw15yuqlISZO0os',
    appId: '1:567166482786:ios:6555ecd8bf7884d0b8d43b',
    messagingSenderId: '567166482786',
    projectId: 'property-listing-fc0de',
    storageBucket: 'property-listing-fc0de.appspot.com',
    iosBundleId: 'com.netkodbilisim.otogaleri',
  );

}