name: Deploy to Docker Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up Docker
        run: docker system prune -af --volumes

      - name: Clear Docker Cache on Remote Host
        run: ssh 206.189.12.215 'sudo docker images | grep "<none>" | awk '{print $3}' | xargs sudo docker rmi'

      - name: Flutter Upgrade
        run: flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Build the Flutter web app
        run: flutter build web --release

      - name: Deploy to Docker Server
        run: docker buildx build --no-cache --platform linux/amd64 --push -t netkodbilisim/otomas-website:$(date +'%Y-%m-%d-%H-%M-%S') -t netkodbilisim/otomas-website:latest .

      - name: Run Image on Server
        run: ssh 206.189.12.215 'sudo docker compose -f otomas-website-production-compose.yaml up --build -d --pull always'

      - name: Read HTML file
        id: read_html
        run: |
          echo "::set-output name=content::$(cat changes.html | tr -d '\n')"

      - name: Send message to Slack
        uses: fjogeleit/http-request-action@v1.2.0
        with:
          url: https://hooks.slack.com/services/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
          method: POST
          headers: '{"Content-Type":"application/json"}'
          data: '{"text": "${{ steps.read_html.outputs.content }}"}'

      - name: Read HTML file
        id: read_html
        run: |
          FILE_PATH="changes.html"
          if [ -f "$FILE_PATH" ]; then
            echo "File contents:"
            CONTENT=$(cat "$FILE_PATH")
            echo "html_content<<EOF" >> $GITHUB_ENV
            echo "$CONTENT" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "File not found!"
            exit 1
          fi

      - name: Send message to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Deploy çıkıldı. https://test.otomas.app\n'"${{ env.html_content }}"'"}' https://hooks.slack.com/services/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
