name: Deploy to Docker Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up Docker
        run: |
          docker system prune -af --volumes

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Add Flutter to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Install dependencies
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build the Flutter web app
        run: flutter build web --release

      - name: Deploy to Docker Server
        run: |
          docker buildx build --no-cache --platform linux/amd64 --push -t netkodbilisim/otomas-website:$(date +'%Y-%m-%d-%H-%M-%S') -t netkodbilisim/otomas-website:latest .