name: Merge to Production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Clean up Docker
        run: |
          docker system prune -af --volumes

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
          flutter channel stable
          flutter upgrade
          flutter config --enable-web

      - name: Build Flutter Web
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter build web --release

      - name: Build Docker Image
        run: |
          docker buildx build --no-cache --platform linux/amd64 --push -t netkodbilisim/otomas-website:$(date +'%Y-%m-%d-%H-%M-%S') -t netkodbilisim/otomas-website:latest .

