name: Deploy to Docker Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Docker Cache on Remote Host
        run: ssh 206.189.12.215 'sudo docker images | grep "<none>" | awk '{print $3}' | xargs -r sudo docker rmi'

      - name: Delete last build
        run: rm -rf build

      - name: Flutter Upgrade
        run: flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Build the Flutter web app
        run: flutter build web --release

      - name: Clean up Docker
        run: docker system prune -af --volumes

      - name: Deploy to Docker Server
        run: docker buildx build --no-cache --platform linux/amd64 --push -t netkodbilisim/otomas-website:$(date +'%Y-%m-%d-%H-%M-%S') -t netkodbilisim/otomas-website:latest .

      - name: Run Image on Server
        run: ssh 206.189.12.215 'sudo docker compose -f otomas-website-production-compose.yaml up --build -d --pull always'
