name: Deploy to Docker Server

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send message to Slack
        run: |
          curl -X POST --data-urlencode "payload={\"username\": \"Flutter Deploy Bot\", \"text\": \"Deploy çıkıldı. https://test.otomas.app.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
